version: '3.4'
services:
    template:
        image: node:16.15
        container_name: GoGrowAPI
        command: ./node_modules/.bin/nodemon
        working_dir: /app
        env_file:
            - .env
        ports:
            - '${APP_PORT}:${APP_PORT}'
        volumes:
            - './src:/app/src'
            - './package.json:/app/package.json'
            - './package-lock.json:/app/package-lock.json'
            - './tsconfig.json:/app/tsconfig.json'
            - './node_modules:/app/node_modules'
            - './nodemon.json:/app/nodemon.json'
        networks:
            - local_network
networks:
    local_network:
        external:
            name: local
